language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python3 Code/item_based.py 547
  - python3 Code/user_based.py 547
  - python3 test/item_testcases.py
  - python3 test/user_testcases.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
